### ISSUE TITLE
Testing Migrate `Domain`

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-cloudfoundry#14]
## Context
We need to migrate our domain to the agreed open-source ready `apigroup`.
The version `v1alpha1` remains unchanged.

## Technical Tasks: 

- Change `apigroup` to `cloudfoundry.crossplane.io`
- Keep version to `v1alpha1`

### Schema change:

- In the CF V3 API, the domain resource does not have `domain` and `subdomain`. 
  - They are in the old api. If full name is not supplied `name` parameter, one can instead specify `domain` and `subdomain`. In this case, `name` is calculated like this `name :=subdomain+.+domain`. 

**[TODO: @dwlou are these Options for End user to decide or the Implementer?]**  The options are available to either use `forProvider.name` or use `forProvider.domain` + `forProvider.subdomain`.   If they are migrating, they just need to change apigroup. If the use is create a new CR, the recommended way is to use `forProvider.name`. 

### Options 
1. Do nothing. Ask user to manually map `domain` and `subdomain` to `name` as `name` as required. 
2. Keep `domain` and `subdomain` and mark them as deprecated field. when `name` is empty, derive full anme from domain and subdomain in a initializer. Report error if neither is provided.  (implemented in #37 )

## Acceptance criteria
- [ ] Implement Schema changes
- [ ] Update migration notes
- [ ] Add Test

**Comment by GenosseOtt** [comment]
## Before
```
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: Domain
metadata:
  namespace: default
  name: my-domain
spec:
  forProvider:
    domain: orchestrator.io
    subDomain: dev
    orgRef:
      name: my-org
    internal: false

```
## After
-  Change apigroup to `cloudfoundry.crossplane.io` 
```
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Domain
metadata:
  namespace: default
  name: my-domain
spec:
  forProvider:
    domain: orchestrator.io
    subDomain: dev
    orgRef:
      name: my-org
    internal: false
```

![Image](https://github.com/user-attachments/assets/f8180bea-d039-4f47-af6a-de9819001e9e)
