### ISSUE TITLE
Testing Migrate `Organization`

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-cloudfoundry#23]
## Migration steps: 

- Change `apiGroup`
- (optional) set `forProvider.name`  to same value as `external-name` annotation 
- (optional) set managementPolicies to Observe only
```
spec:
  managementPolicies: ["Observe"]
```

## Testing:
- create legacy CR and ensure it can reconcile 
- create a new CR by performing the above migration steps
- apply the new CR and ensure it can reconcile

**Comment by GenosseOtt** [comment]
## before
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev
spec:
  forProvider: {}
```
## After 
```yaml 
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup `cloudfoundry.crossplane.io`
kind: Organization
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev # keep external-name
spec:
  forProvider: {}
---
# Alternative
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup `cloudfoundry.crossplane.io`
kind: Organization
metadata:
  namespace: default
  name: my-org-copy
spec:
  forProvider:
    name: cf-dev # set name to the same value as external-name
  managementPolicies: # (optional) set managementPolicies
    - Observe

```

![Image](https://github.com/user-attachments/assets/f3a41e9b-46e2-47a4-b11f-c1ad977f98ea)
