### ISSUE TITLE
Testing Migrate `ServiceInstance`

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-cloudfoundry#24]
## Context
We need to migrate our domain to the agreed open-source ready `apigroup`.
The version `v1alpha1` remains unchanged.

## Technical Steps
- Change `apigroup` to `cloudfoundry.crossplane.io`

### Testing:
- create legacy CR, and ensure it can reconcile
- create a new CR by performing above migration steps 
- apply a new CR, and ensure it can reconcile

## Acceptance criteria
- [ ] Implement Schema changes
- [ ] Update migration notes
- [ ] Add Test

**Comment by GenosseOtt** [comment]
## Case 1
- Before
``` yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceInstance
metadata:
  name: my-service-instance
spec:
  forProvider:
    type: managed
    name: my-service-instance
    spaceRef: 
      name: my-space
      policy: 
        resolve: Always
    servicePlan:
      offering: destination
      plan: lite
```
- After: 
``` yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup `cloudfoundry.crossplane.io`
kind: ServiceInstance
metadata:
  name: my-service-instance
spec:
  forProvider:
    type: managed
    name: my-service-instance
    spaceRef: 
      name: my-space
      policy: 
        resolve: Always
    servicePlan:
      offering: destination
      plan: lite
```

**Comment by GenosseOtt** [comment]
## Case 2: with jsonParams
- Before
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceInstance
metadata:
  name: my-xsuaa
spec:
  forProvider:
    type: managed
    name: my-xsuaa
    spaceRef:
      name: my-space
    servicePlan:
      offering: xsuaa
      plan: application
    jsonParams: |
      {
        "xsappname": "sample-java-app",
        "description": "sample java application",
        "tenant-mode": "shared"
      }

```
- After: 
```yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup "cloudfoundry.crossplane.io"
kind: ServiceInstance
metadata:
  name: my-xsuaa
spec:
  forProvider:
    type: managed
    name: my-xsuaa
    spaceRef:
      name: my-space
    servicePlan:
      offering: xsuaa
      plan: application
    jsonParams: |
      {
        "xsappname": "sample-java-app",
        "description": "sample java application",
        "tenant-mode": "shared"
      }
```

**Comment by GenosseOtt** [comment]
# Case 3: paramsSecretRef
- Secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: xsuaa-parameters
  namespace: crossplane-system
type: Opaque
stringData:
  xsappname: app-with-secret-json
  description: secret java application
  tenant-mode: shared
```
- Before
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceInstance
metadata:
  name: my-xsuaa-secret-ref
spec:
  forProvider:
    type: managed
    name: my-xsuaa-secret-ref
    spaceRef: 
      name: my-space
    servicePlan:
      offering: xsuaa
      plan: application
    paramsSecretRef:
      name: xsuaa-parameters
      namespace: crossplane-system
```
- After: new apigroup
```yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup `cloudfoundry.crossplane.io`
kind: ServiceInstance
metadata:
  name: my-xsuaa-secret-ref
spec:
  forProvider:
    type: managed
    name: my-xsuaa-secret-ref
    spaceRef: 
      name: my-space
    servicePlan:
      offering: xsuaa
      plan: application
    paramsSecretRef:
      name: xsuaa-parameters
      namespace: crossplane-system
```

**Comment by GenosseOtt** [comment]
Case 4: user-provided 

- Credential
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-credentials
  namespace: default
type: Opaque
stringData:
  environmentid: environmentid
  apitoken: apitoken
  apiurl: apiurl
  type: dynatrace
```

- Before
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceInstance
metadata:
  namespace: default
  name: my-ups
spec:
  forProvider:
    type: user-provided
    name: my-ups
    routeServiceUrl: https://my-demo-route-service.example.com
    syslogDrainUrl: syslog-tls://example.log-aggregator.com:6514
    spaceRef: 
      name: my-space
      policy:
        resolve: Always
    credentialsSecretRef: 
        name: dynatrace-credentials
        namespace: default
```
- After: 
```yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigoup `cloudfoundry.crossplane.io`
kind: ServiceInstance
metadata:
  namespace: default
  name: my-ups
spec:
  forProvider:
    type: user-provided
    name: my-ups
    routeServiceUrl: https://my-demo-route-service.example.com
    syslogDrainUrl: syslog-tls://example.log-aggregator.com:6514
    spaceRef: 
      name: my-space
      policy:
        resolve: Always
    credentialsSecretRef: 
        name: dynatrace-credentials
        namespace: default
```
