### ISSUE TITLE
Testing Migrate `ServiceKey`

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-cloudfoundry#25]
## Context
We need to migrate our domain to the agreed open-source ready `apigroup`.
The version `v1alpha1` remains unchanged.

## Technical Tasks: 
- Change `apigroup` to `cloudfoundry.crossplane.io`
- Change `kind` to `ServiceCredentialBinding`
- Use a different secret in `writeConnectionSecretToRef`
[@dwlou  what is a different secret?] means that in the new CR, it must use  a different secret name or a different namespace for the secret. This is because a connectionSecret is created by the CR who writes to it. Other CRs cannot write to the same secret.

- Before
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceKey
metadata:
  name: my-service-key
spec:
  forProvider:
    name: my-service-key
    serviceInstanceRef:
      name: my-service-instance
      policy:
        resolve: Always
    connectionDetailsAsJSON: false
  writeConnectionSecretToRef:
    name: my-service-credential
    namespace: default

``` 
- After
``` yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup
kind: ServiceCredentialBinding # new kind
metadata:
  name: my-service-key
spec:
  forProvider:
    type: key # optional, defaults to "key"
    name: my-service-key
    serviceInstanceRef:
      name: my-service-instance
      policy:
        resolve: Always
    connectionDetailsAsJSON: false
  writeConnectionSecretToRef:
    name: my-service-credential-new # new secret 
    namespace: default

```

Testing:
- create legacy CR, and ensure it can reconcile
- create a new CR by performing above migration steps 
- apply a new CR, and ensure it can reconcile

## Acceptance criteria
- [ ] Implement Schema changes
- [ ] Update migration notes
- [ ] Add Test

**Comment by GenosseOtt** [comment]
- Before
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceKey
metadata:
  name: my-service-key
spec:
  forProvider:
    name: my-service-key
    serviceInstanceRef:
      name: my-service-instance
      policy:
        resolve: Always
    connectionDetailsAsJSON: false
  writeConnectionSecretToRef:
    name: my-service-credential
    namespace: default

``` 
- After
``` yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1 # new apigroup
kind: ServiceCredentialBinding # new kind
metadata:
  name: my-service-key
spec:
  forProvider:
    type: key # optional, defaults to "key"
    name: my-service-key
    serviceInstanceRef:
      name: my-service-instance
      policy:
        resolve: Always
    connectionDetailsAsJSON: false
  writeConnectionSecretToRef:
    name: my-service-credential-new # new secret 
    namespace: default

```
