### ISSUE TITLE
Support CloudFoundry `ServiceKey`/`ServiceCredenialBinding ` rotation

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-cloudfoundry#26]
## Context
We orchestrate Keys to our CloudFoundry Service instances using the CloudFoundry Provider.
For security reasons, we **want to rotate them frequently.**

This is what key rotation looks and feels like for non-cf service instances managed by BTP Service Operator. This approach we are aiming for,

```yaml 
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: sample-binding
spec:
  serviceInstanceName: sample-instance
  secretName: sample-binding-secret
  credentialsRotationPolicy:
    enabled: true
    rotatedBindingTTL: 48h
    rotationFrequency: 600h
```
     

## User Stories
There are 3 scenarios in which Keys are orchestrated and need to be considered for their rotation.

### Key is managed by `ServiceCredenialBinding` with type `key`
![Image](https://github.com/user-attachments/assets/a20151b7-97c7-4540-84bf-b335212dae02)

In this case the `key` is passed to consumer(user) directly. He can either using a k8s `Secret` or the service key in CF directly.  So to rotate `key` or `secret`, you must recreate the `ServiceCredentialBinding` so that the secret is written with new service credentials. 

Handling the secret itself does not trigger any `key rotation`. For example, if you delete the secret, the controller will simply recreate the secret during the next reconciliation but write the same credential into it. 

### key is managed by creating a binding using `ServiceCredentialBinding` with type `app`

These are named service bindings. The key is directly delivered to an app. There is no secret handling in the control-plane involved here.  To rotate the key, we need unbind and bind the service again. 

### Key is managed by configuring services in `App` resource

We could trigger rotation by starting a blue-green update of the app. All services will be bound to the Green app will have a new credentials.

## Technical Steps
@dwlou  for guidance

## Stakeholder 
- Denes Csizmadia

## Acceptance Criteria
- [x] Implemented & Tested
- [x] Described in End user guide
