### ISSUE TITLE
Validate Discoverability of CF resources using `external-name`

### ISSUE THREAD

**Issue by GenosseOtt** [SAP/crossplane-provider-cloudfoundry#50]
## Context
With the growing adoption of IaD/Crossplane in many orgs, we want to invest out test/quality mindset to offer most flexible CRs.

For end-users it is not only valuable that they can create and order new resources in code but also to **bring existing landscapes into managed resources**.  To that end, we need to harmonise ways to import existing CF resources. 

This issue is about validate the current behaviour of importing (starting with `Organization`, `Space`, and `ServiceInstance`) then understand the next steps we need to do to harmonise the import mechanism. 

## Technical Steps
- Create a Control-plane with Provider installed and ProviderConfig in place
- Create ressources via CLI / BTP Cockpit 
- Import resources using `external-name` annotation  with empty or bare-minimal `forProvider`
- Ensure Resource is discovered and can be observed
- Record the reconciled resources 
- Ensure imported resource can be updated 
- Delete resource

## Acceptance Criteria

- Test `Organization` can be imported via `external-name` and `name`
- Test `Space`s can be imported via `external-name` and `name` and `orgRef`
- Test `SpaceRole`s can be imported via `external-name` 
- Test `OrgRole`s can be imported via `external-name` 
- Test `ServiceInstances`s can be imported  via `external-name` and `spaceRef`
- Test `ServiceCredentialBinding`s can be imported  via `external-name`

## Out of scope
- Add follow-up item for next Resources to test following this approach (@dwlou)
- Ensure `SpaceMembers`s can be imported
- Ensure `OrgMembers`s can be imported

**Comment by GenosseOtt** [comment]
Related: https://github.com/SAP/crossplane-provider-btp/issues/162

**Comment by GenosseOtt** [comment]
`external-name` is useful for importing an individual resource. However, to bring existing landscapes into managed resources, we need to think how to represent the `relationship` between resources too.  For example, we want that the imported Space CR is referencing the imported Organization CR.

**Comment by GenosseOtt** [comment]
Examples to import an existing `Oganization`

```yaml
# import by GUID (external-name)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: 8d47af7d-d8ff-494b-a6ff-60fe1aec648d  
spec:
  forProvider: {}

# import by matching name
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
spec:
  forProvider:
    name: cf-dev
  managementPolicies:
    - Observe
---
# import by external-name (name) (legacy)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev # this will be changed to GUID after successful import.
spec:
  forProvider: {}
---


```

**Comment by GenosseOtt** [comment]
Examples to import `Space`

```yaml
# import by guid (external-name)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Space
metadata:
  namespace: default
  name: my-space
  annotations:
    crossplane.io/external-name: 559d3548-7218-4696-9b9d-bc8c3ddfb124
spec:
  forProvider: {}
``` 

```yaml
# Import by matching `name` and `orgRef` 
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Space
metadata:
  namespace: default
  name: my-space
spec:
  forProvider:
    name: space-test
    orgRef:
      name:  my-org
```

**Comment by GenosseOtt** [comment]
Import ServiceInstance

```yaml
# import by guid

apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  namespace: default
  name: my-service-instance
  annotations:
    crossplane.io/external-name: 559d3548-7218-4696-9b9d-bc8c3ddfb124 
spec:
  forProvider: {}   
```

```yaml
# import by name and spaceRef

apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  namespace: default
  name: my-service-instance
spec:
  forProvider: 
       name:  my-destination
       spaceRef: 
           name: my-space
```

**Comment by sdomarecki-sap** [comment]
# Validation results

Software used in the testing:
| Component | Version |
| --- | --- |
| Crossplane | 1.19.0 |
| [BTP provider](https://github.com/SAP/crossplane-provider-btp/tree/v1.1.2) | 1.1.2 |
| [Cloudfoundry provider ](https://github.com/SAP/crossplane-provider-cloudfoundry/tree/v0.3.0) | 0.3.0 |

## MCP and CF provider setup

```yaml
apiVersion: core.openmcp.cloud/v1alpha1
kind: ManagedControlPlane
metadata:
  name: dev-mcp
  namespace: project-crossplane-prv-cf-107--ws-dev
spec:
  desiredRegion:
    name: europe
    direction: central
  components:
    apiServer:
      type: GardenerDedicated
    crossplane:
      version: 1.19.0
      providers:
        - name: btp
          version: 1.1.2
    btpServiceOperator:
      version: 0.6.8
[...]
```
Additionaly, the provider was installed using dedicated Provider CR:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: cloudfoundry-opensource
spec:
  package: ghcr.io/sap/crossplane-provider-cloudfoundry/crossplane/provider-cloudfoundry:v0.3.0
```

All the tests were performed using dl_67bc841d75f52e01365e011c@global.corp.sap technical user and cf-provider-107-sa subaccount under SAP Cloud Orchestration Canary global account.


## Cloudfoundry objects

### Organizations
```yaml
# import by GUID (external-name)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org-external-name-guid
  annotations:
    crossplane.io/external-name: 2057899c-8203-416b-9dd9-c625dcee661c
spec:
  forProvider: {}
  managementPolicies:
    - Observe

---
# import by matching name
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org-forprovider
spec:
  forProvider:
    name: cf-provider-107-sa-org
  managementPolicies:
    - Observe

---
# import by external-name (name) (legacy)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org-external-name
  annotations:
    crossplane.io/external-name: cf-provider-107-sa-org
spec:
  forProvider: {}
  managementPolicies:
    - Observe
```

### Spaces
```yaml
# import by guid (external-name)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Space
metadata:
  namespace: default
  name: my-space-external-name-guid
  annotations:
    crossplane.io/external-name: 9009140c-118c-47c4-a0a5-37a61d0291d9
spec:
  forProvider: {}
  managementPolicies:
    - Observe

---
# Import by matching `name` and `orgRef`
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Space
metadata:
  namespace: default
  name: my-space-forprovider
spec:
  forProvider:
    name: cf-provider-107-sa-space
    orgRef:
      name: my-org-forprovider
  managementPolicies:
    - Observe
```

### OrgRoles
```yaml
# create a new org role with org ref
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: OrgRole
metadata:
  namespace: default
  name: my-orgrole-orgref
spec:
  forProvider:
    type: User
    username: co-test-user@example.com
    orgRef:
      name: my-org-forprovider
      policy:
        resolve: Always
  managementPolicies:
    - Observe

---
# create a new org role with org name
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: OrgRole
metadata:
  namespace: default
  name: my-orgrole-orgname
spec:
  forProvider:
    type: Auditor
    username: co-test-user-2@example.com
    orgName: cf-provider-107-sa-org
  managementPolicies:
    - Observe

---
# import org role with external-name (guid)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: OrgRole
metadata:
  namespace: default
  name: my-orgrole-external-name
  annotations:
    crossplane.io/external-name: 53c6375f-4b49-48dc-9051-0abdef012cce
spec:
  forProvider: {}
  managementPolicies:
    - Observe
```

### SpaceRoles
```yaml
# create a new space role with space ref
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: SpaceRole
metadata:
  namespace: default
  name: my-spacerole-spaceref
spec:
  forProvider:
    type: Developer
    username: co-test-user@example.com
    spaceRef:
      name: my-space-forprovider
      policy:
        resolve: Always
  managementPolicies:
    - Observe

---
# import space role with external-name (guid)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: SpaceRole
metadata:
  namespace: default
  name: my-spacerole-external-name
  annotations:
    crossplane.io/external-name: 55438c93-23d9-43cd-adae-bf186d6bac17
spec:
  forProvider: {}
  managementPolicies:
    - Observe
```

### ServiceInstances
```yaml
# Import ServiceInstance with spaceRef
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-servicenstance-spaceref
  namespace: default
spec:
  forProvider:
    type: managed
    name: service-instance
    spaceRef:
      name: my-space-forprovider
      policy:
        resolve: Always
    servicePlan:
      offering: destination
      plan: lite
  managementPolicies:
    - Observe

---
# Import ServiceInstance with external-name (guid)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-servicenstance-external-name
  namespace: default
  annotations:
    crossplane.io/external-name: 416ed10a-220b-479f-bd32-12bc09249f16
spec:
  forProvider:
    type: managed
    name: service-instance
    servicePlan:
      offering: destination
      plan: lite
  managementPolicies:
    - Observe
```

### ServiceCredentialBindings
```yaml
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceCredentialBinding
metadata:
  name: my-scb-forprovider
  namespace: default
spec:
  forProvider:
    name: scb-key
    type: key
    serviceInstanceRef:
      name: my-servicenstance-spaceref
      policy:
        resolve: Always
  connectionDetailsAsJSON: false
  writeConnectionSecretToRef:
    name: scb-key-forprovider
    namespace: default # keep it default, changing it to service-test will cause the test to hang
  managementPolicies:
    - Observe

---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceCredentialBinding
metadata:
  name: my-scb-external-name
  namespace: default
  annotations:
    crossplane.io/external-name: edfc63c8-546b-4c6e-8351-74524f425ed8
spec:
  forProvider:
    name: scb-key
    type: key
  connectionDetailsAsJSON: false
  writeConnectionSecretToRef:
    name: scb-key-external-name
    namespace: default # keep it default, changing it to service-test will cause the test to hang
  managementPolicies:
    - Observe
```

## Results

| Name | Ready | Synced |
| --- | --- | --- |
| Organizations |
| my-org | ok | ok
