### ISSUE TITLE
[BUG] Cannnot reference Space by name in Service Instance

### ISSUE THREAD

**Issue by dwlou** [SAP/crossplane-provider-cloudfoundry#54]
**Describe the bug**

When importing a serviceinstance using external without specifying space or space Ref, the reconcilation fails because of the following error

`Cannot resolve space name. The resource does not implement SpaceScoped  `

**Tested with Provider Version**
v0.3.0

**To Reproduce**

Apply the following resource

```yaml
# Import ServiceInstance with external-name (guid)
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-servicenstance-external-name
  namespace: default
  annotations:
    crossplane.io/external-name: 416ed10a-220b-479f-bd32-12bc09249f16
spec:
  forProvider:
    type: managed
    name: service-instance
    servicePlan:
      offering: destination
      plan: lite
  managementPolicies:
    - Observe
```

**Expected behavior**

Should import the service instance, if GUID is valid.
