### ISSUE TITLE
[FEATURE] The import tool shall support managed-resource-based cross referencing of resources

### ISSUE THREAD

**Issue by gergely-szabo-sap** [SAP/crossplane-provider-cloudfoundry#58]
**Context**

The import tool can build managed resource definitions based on the information acquired through the CloudFoundry API.

Commonly, resources refer to other resources. E.g. a `SpaceRole` managed resource refers to an external `Space` resource using an external resource identifier, i.e., the Space GUID:

```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-developer
spec:
  forProvider:
    type: Developer
    space: b9d8509e-1c83-4b2b-926e-c4d2c7b15083
    username: user1
    origin: sr-origin
```

The import tool handles these resource relations using the GUID values of the referred external resource, as in the example above.

**Scope**

The managed resources of the CloudFoundry provider can express cross-resource relationships by referring to a managed resource rather than the GUID of an external resource. 

An example would be:
```yaml
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-developer
spec:
  forProvider:
    type: Developer
    spaceRef: 
      name: my-space
    username: user1
    origin: sr-origin
```

This flavor of cross-referencing resources is preferred, as it does not rely on temporary GUID identifiers.

The import tool shall be able to generate managed resource definitions of this kind, where other resources are referred to by their names. This kind of cross-referencing is referred to as *managed-resource-based* cross-referencing.

**Out of scope**

Most managed resource definitions support the *label-selector-based* references. The generation of such managed resources is outside of the scope.

**Technical Steps** 

The tool shall be aware of all managed resources if the import tool wants to use /managed-resource-based/ referencing. So, the resource definitions cannot be generated on the fly. First, all managed resource definitions shall be internally generated with GUID-based cross references. After that, the GUID-based references can be migrated into managed-resource-based references.

**Workarounds & Alternatives**

-

**Additional context**

-
